backend/Web/Areas/Admin/ViewModels/UserManagement/PhoneNumberActivation/PhoneNumberActivationDetailsViewModel.cs
using Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.ViewModels.UserManagement.PhoneNumberActivation
{
    public class PhoneNumberActivationDetailsViewModel
    {
        public int Id { get; set; }

        [Display(Name = "SMS Sent")]
        public bool SMSSent { get; set; }

        [Display(Name = "OTP")]
        public string OTP { get; set; }

        [Display(Name = "Expire date")]
        public DateTime ExpireDate { get; set; }

        [Display(Name = "Send again date")]
        public DateTime SendAgainDate { get; set; }

        [Display(Name = "User email")]
        public string UserEmail { get; set; }

        [Display(Name = "Created at")]
        public DateTime CreatedAt { get; set; }

        [Display(Name = "Updated at")]
        public DateTime UpdatedAt { get; set; }
    }
}

backend/Web/Areas/Admin/ViewModels/UserManagement/PhoneNumberActivation/PhoneNumberActivationListViewModel.cs
using Core.Mappers.Web.Admin.UserManagement.PhoneNumberActivation;
using Core.Mappers.Web.Admin.UserManagement.UserActivation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.ViewModels.UserManagement.PhoneNumberActivation
{
    public class PhoneNumberActivationListViewModel
    {
        public List<PhoneNumberActivationViewModelMapper> PhoneNumberActivations { get; set; }
    }
}

backend/Web/Areas/Admin/Controllers/UserManagement/PhoneNumberActivationController.cs
using Core.Services.ActionResultMessage.Abstraction;
using Core.Services.Business.Data.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Admin.ViewModels.UserManagement.PhoneNumberActivation;

namespace Web.Areas.Admin.Controllers.UserManagement
{
    [Authorize(Roles = "Staff")]
    [Area("Admin")]
    [Route("[area]/[controller]")]
    public class PhoneNumberActivationController : Controller
    {
        private readonly IPhoneNumberActivationService _phoneNumberActivationService;

        public PhoneNumberActivationController(
            IPhoneNumberActivationService phoneNumberActivationService)
        {
            _phoneNumberActivationService = phoneNumberActivationService;
        }

        [HttpGet("[action]")]
        public async Task<IActionResult> List()
        {
            var model = new PhoneNumberActivationListViewModel
            {
                PhoneNumberActivations = await _phoneNumberActivationService.GetAllForAdminAsync()
            };

            return View(model);
        }

        [HttpGet("{id:int}/[action]")]
        public async Task<IActionResult> Details(int id)
        {
            var phoneNumberActivation = await _phoneNumberActivationService.GetAsyncWithUser(id);
            if (phoneNumberActivation == null) return NotFound();

            var model = new PhoneNumberActivationDetailsViewModel
            {
                Id = phoneNumberActivation.Id,
                OTP = phoneNumberActivation.OTP,
                SMSSent = phoneNumberActivation.SMSSent,
                ExpireDate = phoneNumberActivation.ExpireDate,
                SendAgainDate = phoneNumberActivation.SendAgainDate,
                UserEmail = phoneNumberActivation.User.Email,
                CreatedAt = phoneNumberActivation.CreatedAt,
                UpdatedAt = phoneNumberActivation.UpdatedAt
            };

            return View(model);
        }
    }
}

backend/Web/Areas/Admin/ViewComponents/ActionResultMessageViewComponent.cs
using Core.Services.ActionResultMessage.Configuration;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.ViewComponents
{
    public class ActionResultMessageViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var actionResultMessage = TempData["Message"] != null ? JsonConvert.DeserializeObject<ActionResultMessage>(TempData["Message"].ToString()) : null;
            return View("ActionResultMessage", actionResultMessage);
        }
    }
}

backend/Web/Areas/Admin/ViewComponents/BooleanResultViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.ViewComponents
{
    public class BooleanResultViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(bool result)
        {
            return View("BooleanResult", result);
        }
    }
}

backend/Web/Areas/Admin/Views/PhoneNumberActivation/Details.cshtml
@using Web.Areas.Admin.ViewModels.UserManagement.PhoneNumberActivation
@model PhoneNumberActivationDetailsViewModel

@{
    ViewData["Title"] = "Phone number activations";
}

<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="float-end">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="phonenumberactivation" asp-action="list" asp-area="admin">Phone number activations</a>
                    </li>
                </ol>
            </div>
            <h4 class="page-title">Details phone number activation</h4>
        </div><!--end page-title-box-->
    </div><!--end col-->
</div>


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @Html.AntiForgeryToken()

                <div class="row">
                    <div asp-validation-summary="ModelOnly" class="invalid-feedback" style="display:block"></div>
                </div>

                <div class="row">
                    <div class="card-body border mb-3">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-check form-switch form-switch-success">
                                    <input asp-for="SMSSent" class="form-check-input">
                                    <label asp-for="SMSSent" class="form-check-label"></label>
                                    <span asp-validation-for="SMSSent" class="invalid-feedback" style="display:block"></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="OTP"></label>
                            <input readonly class="form-control" asp-for="OTP">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="UserEmail"></label>
                            <input readonly class="form-control" asp-for="UserEmail">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="ExpireDate"></label>
                            <input readonly class="form-control" asp-for="ExpireDate">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="SendAgainDate"></label>
                            <textarea readonly class="form-control" asp-for="SendAgainDate"></textarea>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="SendAgainDate"></label>
                            <textarea readonly class="form-control" asp-for="SendAgainDate"></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/Web/Areas/Admin/Views/PhoneNumberActivation/List.cshtml
@using Web.Areas.Admin.ViewModels.UserManagement.PhoneNumberActivation
@model PhoneNumberActivationListViewModel

@{
    ViewData["Title"] = "Phone number activations";
}


<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <h4 class="page-title">Phone number activations</h4>
        </div>
        <!--end page-title-box-->
    </div>
    <!--end col-->
</div>

@await Component.InvokeAsync("ActionResultMessage")

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="phonenumberactivation-table" class="table table-striped mb-0 ">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>
                                    <span class="mr-1" style="pointer-events: none;">@Html.DisplayNameFor(x => x.PhoneNumberActivations.GetEnumerator().Current.UserEmail)</span>
                                </th>
                                <th>
                                    <span class="mr-1" style="pointer-events: none;">@Html.DisplayNameFor(x => x.PhoneNumberActivations.GetEnumerator().Current.OTP)</span>
                                </th>
                                <th>
                                    <span class="mr-1" style="pointer-events: none;">@Html.DisplayNameFor(x => x.PhoneNumberActivations.GetEnumerator().Current.SMSSent)</span>
                                </th>
                                <th>
                                    <span class="mr-1" style="pointer-events: none;">@Html.DisplayNameFor(x => x.PhoneNumberActivations.GetEnumerator().Current.ExpireDate)</span>
                                </th>
                                <th>
                                    <span class="mr-1" style="pointer-events: none;">@Html.DisplayNameFor(x => x.PhoneNumberActivations.GetEnumerator().Current.SendAgainDate)</span>
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int rowCounter = 0;
                                foreach (var phoneNumberActivation in Model.PhoneNumberActivations)
                                {
                                    rowCounter++;

                                    <tr>
                                        <td>
                                            @rowCounter
                                        </td>
                                        <td>@phoneNumberActivation.UserEmail</td>
                                        <td>@phoneNumberActivation.OTP</td>
                                        <td>@await Component.InvokeAsync("BooleanResult", new { result = phoneNumberActivation.SMSSent })</td>
                                        <td>@phoneNumberActivation.ExpireDate.ToString("o")</td>
                                        <td>@phoneNumberActivation.SendAgainDate.ToString("o")</td>
                                        <td>
                                            <a asp-controller="phonenumberactivation" asp-action="details" asp-area="admin" asp-route-id="@phoneNumberActivation.Id"><i class="fas fa-external-link-square-alt text-secondary font-18"></i></a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div><!--end /tableresponsive-->
            </div><!--end card-body-->
        </div><!--end card-->
    </div> <!-- end col -->
</div>